# Generated by Django 2.2.7 on 2019-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
